// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxF6y3L27Ldwg4hTLB63a6To752NDnE8E',
    appId: '1:1088720884242:web:86d3311f5b8bdd3b53becb',
    messagingSenderId: '1088720884242',
    projectId: 'momentum-c905c',
    authDomain: 'momentum-c905c.firebaseapp.com',
    storageBucket: 'momentum-c905c.firebasestorage.app',
    measurementId: 'G-F5KB55S5EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEMbo0x1GPHnZgQfxDW9u0y0LFuboA-1A',
    appId: '1:1088720884242:android:80be81e630b4bcde53becb',
    messagingSenderId: '1088720884242',
    projectId: 'momentum-c905c',
    storageBucket: 'momentum-c905c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-rOENkZOI9XVJqMDm5HGgDdRIuf5P-o',
    appId: '1:1088720884242:ios:31d4922f3e4cb3e653becb',
    messagingSenderId: '1088720884242',
    projectId: 'momentum-c905c',
    storageBucket: 'momentum-c905c.firebasestorage.app',
    iosBundleId: 'com.example.momentum',
  );

}